routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function (){

    Route::get('projects/create/{company_id?}','ProjectsController@create');
    Route::resource('projects','ProjectsController');

    Route::resource('companies','CompaniesController');

    Route::resource('comments','CommentsController');
    Route::resource('roles','RolesController');
    Route::resource('tasks','TasksController');
    Route::resource('users','UsersController');

});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = [
        'name',
        'description',
        'company_id',
        'user_id',
        'days'
    ];


    public function user(){
        return $this->belongsToMany('App\User');
    }

    public function company(){
        return $this->belongsTo('App\Company');
    }

    public function comments(){
        return $this->morphMany('App\Comment','commentable');
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Project;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::where('user_id',Auth::user()->id)->get();

        return view('projects.index',['projects'=>$projects]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($company_id = null)
    {
        //dump([$company_id]);
        $companies = null;
        if(!$company_id){
            $companies = Company::where('user_id',Auth::user()->id)->get();
        }
        return view('projects.create',['company_id'=>$company_id,
                                            'companies'=>$companies]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(Auth::check()){
            $project = Project::create([
                'name'=>$request->input('name'),
                'company_id'=>$request->input('company_id'),
                'description'=>$request->input('description'),
                'user_id'=>Auth::user()->id
            ]);

            if($project){
                return redirect()->route('projects.show',['project'=>$project->id])
                    ->with('success','Project created successfully');
            }
        }

        return back()->withInput()->with('errors','Error creating a project');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        $project = Project::find($project->id);
        //dump($project->comments());
        $comments = $project->comments;
        return view('projects.show',['project'=>$project,'comments'=>$comments]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        $project = Project::find($project->id);
        return view('projects.edit ',['project'=>$project]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //save data

        $projectUpdate = Project::where('id', $project->id)
            ->update([
                'name'=> $request->input('name'),
                'description'=> $request->input('description')
            ]);

        if($projectUpdate){
            return redirect()->route('projects.show', ['project'=> $project->id])
                ->with('success' , 'Project updated successfully');
        }
        //redirect
        return back()->withInput();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        $findCompany = Project::find($project);
        if($findCompany-> delete()){
            return redirect()->route('projects.index')
                ->with('success','Project got deleted successfully');
        }
        return back()->withInput()->with('error','Compnay could not be deleted');
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app')
@section('content')

    <div class="row col-md-9 col-lg-9 col-sm-9 pull-left" style="background:white">
        <h1> Create new project </h1>
        <!-- Example row of columns -->
        <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin : 10px">

            <form method="post" action="{{ route('companies.store') }}">
                {{ csrf_field() }}

                <div class="form-group">
                    <label for="project-name">Name<span class="required">*</span></label>
                    <input placeholder="Enter name"
                           id="project-name"
                           required
                           name="name"
                           spellcheck="false"
                           class="form-control"
                    />
                </div>

                @if($companies == null)
                    <input class="form-control" name="company_id" type="hidden" value="{{$company_id}}"/>
                @endif
                @if($companies != null)
                    <div class="form-group">
                        <label for="select-company">Select company </label>
                        <select name="company_id" class="form-control">
                            @foreach($companies as $company)
                                <option value="{{$company->id}}">{{$company->name}}</option>
                            @endforeach

                        </select>

                    </div>
                @endif

                <div class="form-group">
                    <label for="project-content">Description</label>
                    <textarea placeholder="Enter description"
                              style="resize: vertical"
                              id="project-content"
                              name="description"
                              rows="5" spellcheck="false"
                              class="form-control autosize-target">
                    </textarea>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Submit">
                </div>
            </form>
        </div>

        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    </div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')
@section('content')

    <div class="col-md-9 col-lg-9 pull-left">

        <!-- Example row of columns -->
        <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin : 10px">

            <form method="post" action="{{ route('companies.update',[$company->id]) }}">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="put">

                <div class="form-group">
                    <label for="company-name">Name<span class="required">*</span></label>
                    <input placeholder="Enter name"
                           id="company-name"
                           required
                           name="name"
                           spellcheck="false"
                           class="form-control"
                           value="{{ $company->name }}"
                    />
                </div>

                <div class="form-group">
                    <label for="company-content">Description</label>
                    <textarea placeholder="Enter description"
                              style="resize: vertical"
                              id="company-content"
                              name="description"
                              rows="5" spellcheck="false"
                              class="form-control autosize-target">
                                          {{ $company->description }}</textarea>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Submit">
                </div>
            </form>
    </div>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    </div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <div class="panel panel-primary ">
            <div class="panel-heading">Projects
                <a class="pull-right btn btn-primary btn-sm" href="/projects/create">Add <i class="fa fa-plus" aria-hidden="true"></i>  </a>
            </div>
            <div class="panel-body">
                <ul class="list-group">
                    @foreach($projects as $project)
                        <li class="list-group-item"><a href="/projects/{{ $project->id}}">{{$project->name}}</a></li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')
@section('content')

    <div class="col-md-9 col-lg-9 pull-left">

        <!-- The justified navigation menu is meant for single line per list item.
             Multiple lines will require custom code not provided by Bootstrap. -->
        <!-- Jumbotron -->
        <div class="well well-lg">
            <h1>{{$project->name}}!</h1>
            <p class="lead">{{$project->description}}</p>
            <!--<p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p> -->
        </div>

        <!-- Example row of columns -->

        <!-- For including the comments-->
        @include('partials.comments')
        <div class="row col-md-12 col-log-12 col-sm-12" style="background: white;margin: 10px;">
            <a href="/projects/create" class="pull-right btn btn-default btn-sm">Add project</a>

            <div class="container-fluid">
                <form method="post" action="{{ route('comments.store') }}">
                    {{ csrf_field() }}

                    <input type="hidden" name="commentable_type" value="App\Project">
                    <input type="hidden" name="commentable_id" value="{{$project->id}}">

                    <div class="form-group">
                        <label for="comment-contents">Comment</label>
                        <textarea placeholder="Enter comment"
                                  style="resize: vertical"
                                  id="comment-contents"
                                  name="body"
                                  rows="3" spellcheck="false"
                                  class="form-control autosize-target">
                    </textarea>
                    </div>

                    <div class="form-group">
                        <label for="url-desc">Proof of work</label>
                        <textarea placeholder="Enter url or screenshots"
                                  style="resize: vertical"
                                  id="url-desc"
                                  name="url"
                                  rows="2" spellcheck="false"
                                  class="form-control autosize-target">
                    </textarea>
                    </div>


                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="Submit">
                    </div>
                </form>
            </div>

        </div>

    </div>

    <div class="col-sm-3 col-md-3  col-lg-3 pull-right">
        <!--<div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
        </div>-->


        <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
                <li><a href="/projects/{{$project->id}}/edit">Edit</a></li>
                <li><a href="/projects/create">Create project</a></li>
                <li><a href="/projects/index">My projects</a></li>
                <br/>
                @if($project->user_id == Auth::user()->id)
                    <li>
                        <a href="#" onclick="
                          var result = confirm('Are you sure you wish to delete this project ?');
                              if( result ){
                                      event.preventDefault();
                                      document.getElementById('delete-form').submit();
                              }"
                        >
                            Delete
                        </a>

                        <form id="delete-form" action="{{ route('companies.destroy',[$project->id]) }}"
                              method="POST" style="display: none;">
                            <input type="hidden" name="_method" value="delete">
                            {{ csrf_field() }}
                        </form>
                    </li>
                @endif
            </ol>
        </div>

        <!--
        <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
                <li><a href="#">March 2014</a></li>
            </ol>
        </div>-->

    </div>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
@endsection